### ISSUE TITLE
instead of Matlab is there python implementation for this 

### ISSUE THREAD

**Issue by shahdivyam** [sergeyk/selective_search_ijcv_with_python#22]
Or any other model which can give bounding boxes from the input images using python. Or can we execute it using octave
Thanks

**Comment by eugene123tw** [comment]
I have the same problem. 
I hope readme.md can mention it if matlab is mandatory.

**Comment by shahdivyam** [comment]
Eventually I figured out that Matlab is mandatory for the model to run.
