### ISSUE TITLE
problem running selective_search.py

### ISSUE THREAD

**Issue by mees** [sergeyk/selective_search_ijcv_with_python#7]
Hey guys,
I am trying to run the caffe rcnn detection and after running selective_search.py I get following error:

Traceback (most recent call last):
  File "python/selective_search_ijcv_with_python/selective_search.py", line 63, in <module>
    boxes = get_windows(image_filenames)
  File "python/selective_search_ijcv_with_python/selective_search.py", line 36, in get_windows
    shlex.split(mc), stdout=open('/dev/null', 'w'), cwd=script_dirname)
  File "/usr/lib/python2.7/subprocess.py", line 710, in **init**
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

As fas as I can tell, I have caffe, matlab and python bindings installed correctly. The rcnn matlab demo was also correctly executed.

**Comment by mees** [comment]
Problem was solved by exporting in .bashrc PATH=$PATH:/usr/local/MATLAB/R2012a/bin, before I had an alias defined for the binary.

**Comment by Lvhhhh** [comment]
@mees  
 scipy.io.matlab.miobase.MatReadError: Mat file appears to be empty
what can i do?

**Comment by ycxia** [comment]
@mees @sergeyk 
I meet the same problem. I run demo.m in my computer and then unload selective_search_ijcv_with_python to server(without install matlab).
Does this work?
